# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           http://gstarr.me/projects
relative_permalinks: true

# Setup
title:               Graham Starr's Projects
tagline:             ''
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://gstarr.me/projects
baseurl:             '/projects/'
paginate:            5

# About/contact
author:
  name:              Graham Starr
  url:               https://twitter.com/grahamstarr
  email:             hello@gstarr.me

# Custom vars
version:             
