# Site settings
title:       Projects | Graham Starr
email:       hello@gstarr.me
author:      Graham Starr
description: "Graham Starr's projects, hosted on Github."
baseurl:     "/projects"
url:         "http://gstarr.me/projects"
date_format: "%b %-d, %Y"

# Google services
google_analytics:
google_verification:

# Optional features
animated:             true
show_related_posts:   true
show_post_footers:    true
show_social_icons:    true
ajaxify_contact_form: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments: 
facebook_appid: 
facebook_comments_number: 10

# Social icons
github_username: gstarr
dribbble_username: gstarr
bitbucket_username:
stackoverflow_id:
twitter_username: grahamstarr
google_plus_id:
linkedin_username: grahamstarr
angellist_username:
medium_id: 
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data', 'no_intra_emphasis', 'fenced_code_blocks', 'strikethrough', 'highlight', 'underline', 'footnotes']
permalink:    pretty
paginate:     10
sass:
  compressed: true
