# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Projects | Graham Starr
tagline:             ''
description:         'A projects page for <a href="http://gstarr.me" target="_blank">Graham Starr</a>, built with Jekyll using <a href="https://github.com/poole/lanyon" target="_blank">Lanyon</a>.'
url:                 http://gstarr.me/projects
baseurl:             '/projects'
paginate:            5

# About/contact
author:
  name:              Graham Starr
  url:               http://gstarr.me/
  email:             hello@gstarr.me

# Custom vars
version:             
