# Site settings
title: Graham Starr's Projects
email: hello@gstarr.me
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/projects/"
url: "http://gstarr.me/projects" # the base hostname & protocol for your site
twitter_username: grahamstarr
github_username:  gstarr

# Build settings
markdown: kramdown
